version: "2"
run:
  build-tags:
    - windows
    - integration
    - unit
    - e2e
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unparam
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (github.com/saltosystems/x/log.Logger).Error
        - (github.com/saltosystems/x/log.Logger).Info
        - (github.com/saltosystems/x/log.Logger).Warn
        - (github.com/saltosystems/x/log.Logger).Debug
    gocritic:
      disabled-checks:
        - unnamedResult
      enabled-tags:
        - diagnostic
        - style
        - performance
    gosec:
      excludes:
        - G103  # Unsafe pointer usage required for COM/WinRT interop
        - G115  # Integer conversions are safe in this context
        - G301  # Directory permissions for generated code
    govet:
      enable:
        - shadow
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: unused-parameter
          disabled: true
    staticcheck:
      checks:
        - "-QF1001"  # De Morgan's law - style preference
        - "-ST1023"  # Type inference - style preference
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: declaration of "err|ctx|ok" shadows declaration at
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
